name: Push release version
on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - uses: actions/checkout@master
      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:11})
      - name: Publish latest tag to registry
        env:
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
            DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker version
          docker login -u "$DOCKER_USER" -p "$DOCKER_PASSWORD"
          docker build -t lkdevelopment/hetzner-cloud-api-mock::$RELEASE_VERSION .
          docker push lkdevelopment/hetzner-cloud-api-mock::$RELEASE_VERSION
